name: Windows Build

on:
  push:
    branches: [ 3d-rendering, version-* ]
  pull_request:
    branches: [ 3d-rendering ]

env:
  VULKAN_SDK_VERSION: "1.3.280.0"
  CMAKE_VERSION: "3.25.3"

jobs:
  build-windows:
    runs-on: windows-2022

    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]
        compiler: [msvc]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup MSVC
        uses: microsoft/setup-msbuild@v2

      - name: Setup Visual Studio environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Install CMake 3.25+
        uses: jwlawson/actions-setup-cmake@v1.14
        with:
          cmake-version: '${{ env.CMAKE_VERSION }}'

      - name: Verify CMake version
        run: cmake --version

      - name: Install Vulkan SDK
        uses: humbletim/install-vulkan-sdk@v1.2
        with:
          version: ${{ env.VULKAN_SDK_VERSION }}
          cache: true

      - name: Set Vulkan environment variables
        shell: powershell
        run: |
          echo "VULKAN_SDK: $env:VULKAN_SDK"
          echo "VK_SDK_PATH: $env:VK_SDK_PATH"
          echo "VULKAN_SDK=$env:VULKAN_SDK" >> $env:GITHUB_ENV
          echo "VK_SDK_PATH=$env:VK_SDK_PATH" >> $env:GITHUB_ENV

      - name: Verify glslc availability
        shell: cmd
        run: |
          where glslc || echo "glslc not found in PATH, checking Vulkan SDK..."
          if exist "%VULKAN_SDK%\Bin\glslc.exe" (
            echo "Found glslc in Vulkan SDK"
            echo "%VULKAN_SDK%\Bin" >> %GITHUB_PATH%
          ) else (
            echo "ERROR: glslc not found!"
            exit /b 1
          )

      - name: Cache CMake build dependencies
        uses: actions/cache@v4
        with:
          path: |
            build/_deps
          key: cmake-deps-windows-${{ matrix.build_type }}-${{ hashFiles('CMakeLists.txt') }}
          restore-keys: |
            cmake-deps-windows-${{ matrix.build_type }}-
            cmake-deps-windows-

      - name: Configure CMake
        shell: cmd
        run: |
          mkdir build
          cd build
          cmake .. ^
            -G "Visual Studio 17 2022" ^
            -A x64 ^
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} ^
            -DVULKAN_SDK_PATH="%VULKAN_SDK%"

      - name: Build project
        shell: cmd
        run: |
          cd build
          cmake --build . --config ${{ matrix.build_type }} --parallel %NUMBER_OF_PROCESSORS%

      - name: Build shaders
        shell: cmd
        run: |
          cd build
          cmake --build . --target LiaraShaders --config ${{ matrix.build_type }}

      - name: Test executable
        shell: cmd
        run: |
          cd build
          cd app
          dir ${{ matrix.build_type }} /b
          if exist "${{ matrix.build_type }}\Demo.exe" (
            echo "Demo.exe found successfully"
          ) else (
            echo "ERROR: Demo.exe not found!"
            dir ${{ matrix.build_type }} /s
            exit /b 1
          )

      - name: Upload artifacts (Release builds on version tags)
        if: matrix.build_type == 'Release' && startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-artifact@v4
        with:
          name: liara-engine-windows-${{ matrix.build_type }}-${{ github.ref_name }}
          path: |
            build/${{ matrix.build_type }}/Demo.exe
            build/${{ matrix.build_type }}/*.dll
            build/shaders/*.spv
            assets/
          retention-days: 30

      - name: Upload build logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs-windows-${{ matrix.build_type }}-${{ github.run_number }}
          path: |
            build/CMakeFiles/CMakeOutput.log
            build/CMakeFiles/CMakeError.log
            build/**/*.log
          retention-days: 7